version: "3.3"

services:
  backend:
    build: ./server
    networks:
      - web
      - default
    labels:
      - "traefik.backend=stream_backend"
      - "traefik.docker.network=web"
      - "traefik.basic.frontend.rule=Host:streamserver.solderneer.me"
      - "traefik.enable=true"
      - "traefik.basic.port=3000"
  frontend:
    build: ./client
    networks:
      - web
      - default
    labels:
      - "traefik.backend=stream_frontend"
      - "traefik.docker.network=web"
      - "traefik.basic.frontend.rule=Host:stream.solderneer.me"
      - "traefik.enable=true"
      - "traefik.basic.port=80"
networks:
    web:
        external: true
