version: "3.3"

services:
  backend:
    build: ./server
    command: npm run dev
    volumes: 
      - ./server:/app
    ports: 
      - "3000:3000"
  frontend:
    build: ./client
    command: npm run serve
    volumes:
      - ./client:/app
    ports:
      - "80:8080"
  file-server:
    build: ./file-server
    volumes:
      - ./movies:/etc/nginx/movies
    ports:
      - "1000:80"